pluginManagement {
  repositories {
      maven { url = 'https://maven.vaadin.com/vaadin-prereleases' }
      gradlePluginPortal()
  }
  plugins {
      id 'com.vaadin' version "${vaadinVersion}"
  }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}
rootProject.name = 'GreenPages'
include 'green.yp.api'
include 'green.yp.backend'
include 'usps.address.api'
