DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
END;
ALTER TABLE producer_contact MODIFY COLUMN generic_contact_name varchar(100);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;