DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
END;
ALTER TABLE `producer`
    ADD COLUMN `icon_link_url` varchar(255)
    after website_url;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;