DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
END;
ALTER TABLE producer MODIFY COLUMN name varchar(150);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;