DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
END;
    ALTER TABLE producer_contact ADD COLUMN title varchar(60) after last_name;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;