DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;
    DROP TABLE classified_invoice_payment;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;