DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;
    ALTER TABLE classified ADD COLUMN id_token varchar(20) after per_unit_type;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;