DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;
    ALTER TABLE payment_transaction MODIFY COLUMN error_body text;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;