DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;
    ALTER TABLE producer_audit MODIFY COLUMN ip_address varchar(50);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;