DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `line_of_business` ADD COLUMN `icon_file_name` varchar(100) after icon_name;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;