DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;
    DROP TABLE contact_message;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;