server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/greenyp
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      minimum-idle: 0
      max-lifetime: 120000
      idle-timeout: 120000
    username: gypadmin
    password: gypadmin
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIAYDWHTBKKSTP5KN62
    password: BJOPg6J3zZwsns6BGAH6odIXMyiwoyRnSz57ND7jfNQ7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            audiences: 922748b0-1658-4880-942a-36eaca3aa185
            issuer-uri: http://localhost:9011
circuitbreaker:
  instances:
    geocode-api:
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3
fusionauth:
  green:
    yp:
      apiKey: xwlV_d5Xa7sy2WmF3VnHA0Miegr6NU24Kc7xqHyQA7RhznwuBNoJOLgr
      baseUrl: http://localhost:9011
      host: http://localhost:9011
      client:
        id: 922748b0-1658-4880-942a-36eaca3aa185
        secret: Nso5YJaHpIl6_vNezTylWDUoeKhb7eymmn1b_76Gx74
      app:
        id: 922748b0-1658-4880-942a-36eaca3aa185
      tenant: e5c8b6b2-ca40-4d53-c435-01e1b803db88
      connectTimeout: 2000
      readTimeout: 2000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
greenyp:
  jwt:
    decoderUrl: http://localhost:9011/.well-known/jwks.json
  cloud:
    aws:
      s3:
        enabled: false
        region: us-east-1
  geocoder:
    impl: aws
    aws:
      placeIndex: GreenypPlaceIndex
    opencage:
      url: https://api.opencagedata.com
      apikey: 8a3613d6f66848d286ea647a4f813d1a
  image:
    service:
      host: http://localhost:8081
      filepath: /Users/luthermaloney/git/Green.Pages/green.yp.backend/build/resources/main/static
resilience4j:
  ratelimiter:
    instances:
      geocode-api:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 100ms
springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: 922748b0-1658-4880-942a-36eaca3aa185
      client-secret: Nso5YJaHpIl6_vNezTylWDUoeKhb7eymmn1b_76Gx74
      scopes: openid,profile
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorization-url: http://localhost:9011/oauth2/authorize
    token-url: http://localhost:9011/oauth2/token