server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${GYP_DB_HOSTNAME}:${GYP_DB_PORT}/greenyp
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      minimum-idle: 0
      max-lifetime: 120000
      idle-timeout: 120000
    username: ${GYP_DB_USERNAME}
    password: ${GYP_DB_PASSWD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  application:
    name: Green YP Market Service APIs
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
fusionauth:
  green:
    yp:
      apiKey: ${GYP_FA_API_KEY}
      baseUrl: http://fusionauth-service-3:9011
      host: http://fusionauth-service-3:9011
      client:
        id: ${GYP_FA_CLIENT_ID}
        secret: ${GYP_FA_CLIENT_SECRET}
      app:
        id: ${GYP_FA_APP_ID}
      tenant: ${GYP_FA_TENANT_ID}
      connectTimeout: 2000
      readTimeout: 2000
greenyp:
  cloud:
    aws:
      s3:
        enabled: true
        region: us-east-1
  image:
    service:
      impl: aws
      host: https://greenyp-public-images.s3.amazonaws.com
      bucket: greenyp-public-images