package com.green.yp.api.apitype.enumeration;

public enum AuditActionType {
  CREATE_LINE_OF_BUSINESS,
  UPDATE_LINE_OF_BUSINESS,
  LOG_ACTION,
  CREATE,
  UPDATE,
  PATCH,
  DISCONTINUE_PRODUCT,
  DELETE_LOCATION,
  DELETE,
  CANCEL_ACCOUNT,
  BAD_AUTH_ATTEMPT
}
