package com.green.yp.api.apitype.enumeration;

public enum AuditObjectType {
  LINE_OF_BUSINESS,
  SUBSCRIPTION,
  OBJECT,
  CREATE_LOB_SERVICE,
  UPDATE_LOB_SERVICE,
  PRODUCER,
  PRODUCER_LOCATION,
  PRODUCER_CONTACT,
  PRODUCER_SERVICE,
  PRODUCER_PRODUCT,
  PRODUCER_LOCATION_HOURS,
  BAD_AUTH_ATTEMPT
}
