name: deploy_latest_services.yml

on:
  workflow_dispatch:  # manual trigger

jobs:
  redeploy:
    name: Force ECS service to redeploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: fusionauth-fargate-cluster
      SERVICE_NAME: greenyp-services-api

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get current task definition ARN
        id: get-task-def
        run: |
          TASK_DEF_ARN=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME \
            --query "services[0].taskDefinition" \
            --output text)
          echo "task_definition_arn=$TASK_DEF_ARN" >> "$GITHUB_OUTPUT"

      - name: Force new deployment with existing task definition
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition ${{ steps.get-task-def.outputs.task_definition_arn }} \
            --force-new-deployment

